#pragma once
enum {
    Oconnectallwithgrid = 1053147,
    CONNECT_ALL_WITH_GRID_CONNECT_ALL_WITH_GRID_GROUP = 1000,
    CONNECT_ALL_WITH_GRID_CONNECT_ALL_WITH_GRID_OBJECTS = 1001,
    CONNECT_ALL_WITH_GRID_CONNECT_ALL_WITH_GRID_GRID_UNIT = 1002,
    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_GROUP = 1003,
    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_LENGTH_UNITS = 1004,
    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION = 1005,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_XP = 0,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_YP = 1,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_ZP = 2,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_ = -1,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_XN = 3,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_YN = 4,
        CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_ZN = 5,
};
