CONTAINER Oconnectallwithgrid {
    INCLUDE Obase;
    NAME Oconnectallwithgrid;
    GROUP ID_OBJECTPROPERTIES {
    }
    GROUP CONNECT_ALL_WITH_GRID_CONNECT_ALL_WITH_GRID_GROUP {
        DEFAULT 1;
        IN_EXCLUDE CONNECT_ALL_WITH_GRID_CONNECT_ALL_WITH_GRID_OBJECTS { ANIM OFF; }
        REAL CONNECT_ALL_WITH_GRID_CONNECT_ALL_WITH_GRID_GRID_UNIT { DEFAULT 10.0; MIN 0.0; STEP 1.0; UNIT METER; }
        GROUP CONNECT_ALL_WITH_GRID_STEM_TO_GRID_GROUP {
            DEFAULT 1;
            REAL CONNECT_ALL_WITH_GRID_STEM_TO_GRID_LENGTH_UNITS { DEFAULT 1.0; MIN 0.0; MAX 1000.0; STEP 1.0; }
            LONG CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION {
                CUSTOMGUI CYCLEBUTTON;
                CYCLE {
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_XP;
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_YP;
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_ZP;
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_;
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_XN;
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_YN;
                    CONNECT_ALL_WITH_GRID_STEM_TO_GRID_DIRECTION_ZN;
                }
            }
        }
    }
}
